FROM openjdk:23-slim
EXPOSE 8080

ARG DB_ADDRESS_ARG=localhost
ARG DB_NAME_ARG=duty_manager
ARG DB_USERNAME_ARG=backend_1
ARG DB_PASSWORD_ARG=backend_1
ARG JWT_KEY_ARG=asdasdada
ARG SERVER_PORT_ARG=8080
ARG SERVER_ADDRESS_ARG=192.168.0.204
ARG FRONTEND_ADDRESS_ARG=localhost

ENV DB_ADDRESS=${DB_ADDRESS_ARG}
ENV DB_NAME=${DB_NAME_ARG}
ENV DB_USERNAME=${DB_USERNAME_ARG}
ENV DB_PASSWORD=${DB_PASSWORD_ARG}
ENV JWT_KEY=${JWT_KEY_ARG}
ENV SERVER_PORT=${SERVER_PORT_ARG}
ENV SERVER_ADDRESS=${SERVER_ADDRESS_ARG}
ENV FRONTEND_ADDRESS=${FRONTEND_ADDRESS_ARG}

COPY target/duty-manager-backend-0.0.1-SNAPSHOT.jar duty-manager-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/duty-manager-backend-0.0.1-SNAPSHOT.jar"]
