spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
application:
  security:
    jwt:
      secret-key: ${JWT_KEY}
      expiration: 3600000
