spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
application:
  security:
    jwt:
      secret-key: ${JWT_KEY}
      expiration: 64800000
server:
  address: ${SERVER_ADDRESS}
  port: ${SERVER_PORT}
frontend:
  address: ${FRONTEND_ADDRESS}
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
